id: P000144
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད།
  authors:
  - མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་ཡོན་ཏན་རྒྱ་མཚོ།
  - མཛད་པ་པོ། འཇུ་མི་ཕམ་འཇམ་དཔལ་དགྱེས་པའི་རྡོ་རྗེ།
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
  id: RDI-SS-06
web_metadata:
  title:
    en: A Selection of Texts on the Meaning of the Final Turning of the Wheel
    bo: འཁོར་ལོ་མཐའ་མའི་དགོངས་དོན་གཅེས་བཏུས།
  collection:
    en: RDI Study Series–  Book 6
    bo: ཐོས་བསམ་འཆད་ཉན་གྱི་རིམ་པ།–  དེབ། ༦
  author:
    en: Authors:Jamgon Kongtrul Lodro Thaye,Jamgon Mipham Gyatso
    bo: འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།,འཇམ་མགོན་མི་ཕམ་རྒྱ་མཚོ།
  pusblisher:
    en: Rigpe Dorje Institute
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-SS-06
  category:
    en: Buddha Nature
    bo: བདེ་གཤེགས་སྙིང་པོ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-SS-06.epub
  description:
    en: ༄༅། །ངོ་བོ་སྟོང་པའི་ཆ་བརྗོད་བྱའི་གཙོ་བོར་བྱས་པ་དང་། རང་བཞིན་ལྷུན་གྲུབ་ཀྱི་ཆ་བརྗོད་བྱའི་གཙོ་བོར་བྱས་པ་སྟེ་ཡང་གསལ་བར་བརྗོད་ན་སྟོང་ཉིད་མེད་དགག་དང་མ་ཡིན་དགག་ཏུ་སྨྲ་བའི་ཁྱད་པར་རོ།
      །ཁ་ཕྱི་བལྟས་དང་ནང་བལྟས་ཀྱི་བཤད་ཚུལ་དཔྱད་པ་དང་སྒོམ་པའི་དོན་གཉིས་སུ་སོང་བ་ཡིན་ནོ་ཞེས་རྒྱུད་འགྲེལ་སེངྒེའི་ང་རོ་ལས་༧རྗེ་འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས་ཀྱིས་གསུངས་པ་ལྟར་ཡིན།
      བཤད་ཚུལ་གཉིས་པོ་དེ་ལ་བོད་གངས་ཅན་གྱི་ལྗོངས་སུ་དབུ་མ་རང་སྟོང་དང་དབུ་མ་གཞན་སྟོང་ཞེས་གྲགས་ཤིང་།
      དེ་དག་བོད་སྟོན་རྣམས་ཀྱིས་རང་བཟོར་བྱས་པ་ཡང་མ་ཡིན་ཞིང་གོང་གསལ་གནས་སྐབས་སྤྲོས་པ་གཅོད་པའི་ངེས་དོན་དང་།
      མཐར་ཐུག་གནས་ལུགས་དོན་དམ་གཏན་ལ་དབབ་པའི་ངེས་དོན་དུ་གནས་པ་འཁོར་ལོ་བར་མཐའ་གསུང་རབ་དགོངས་འགྲེལ་དང་བཅས་པའི་གསུང་སྒྲོས་ཉིད་ལ་གཞན་སྟོང་ཞེས་པའི་མིང་བླ་དྭགས་སུ་བཏགས་པ་ཡིན་ནོ།
      །
    bo: ༄༅། །ངོ་བོ་སྟོང་པའི་ཆ་བརྗོད་བྱའི་གཙོ་བོར་བྱས་པ་དང་། རང་བཞིན་ལྷུན་གྲུབ་ཀྱི་ཆ་བརྗོད་བྱའི་གཙོ་བོར་བྱས་པ་སྟེ་ཡང་གསལ་བར་བརྗོད་ན་སྟོང་ཉིད་མེད་དགག་དང་མ་ཡིན་དགག་ཏུ་སྨྲ་བའི་ཁྱད་པར་རོ།
      །ཁ་ཕྱི་བལྟས་དང་ནང་བལྟས་ཀྱི་བཤད་ཚུལ་དཔྱད་པ་དང་སྒོམ་པའི་དོན་གཉིས་སུ་སོང་བ་ཡིན་ནོ་ཞེས་རྒྱུད་འགྲེལ་སེངྒེའི་ང་རོ་ལས་༧རྗེ་འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས་ཀྱིས་གསུངས་པ་ལྟར་ཡིན།
      བཤད་ཚུལ་གཉིས་པོ་དེ་ལ་བོད་གངས་ཅན་གྱི་ལྗོངས་སུ་དབུ་མ་རང་སྟོང་དང་དབུ་མ་གཞན་སྟོང་ཞེས་གྲགས་ཤིང་།
      དེ་དག་བོད་སྟོན་རྣམས་ཀྱིས་རང་བཟོར་བྱས་པ་ཡང་མ་ཡིན་ཞིང་གོང་གསལ་གནས་སྐབས་སྤྲོས་པ་གཅོད་པའི་ངེས་དོན་དང་།
      མཐར་ཐུག་གནས་ལུགས་དོན་དམ་གཏན་ལ་དབབ་པའི་ངེས་དོན་དུ་གནས་པ་འཁོར་ལོ་བར་མཐའ་གསུང་རབ་དགོངས་འགྲེལ་དང་བཅས་པའི་གསུང་སྒྲོས་ཉིད་ལ་གཞན་སྟོང་ཞེས་པའི་མིང་བླ་དྭགས་སུ་བཏགས་པ་ཡིན་ནོ།
      །
